name: MSXmerge composer

on:
  push:
    branches:
      - master
    paths:
      - 'gfx/MSXmerge/**'
      - '.github/workflows/msxmerge_ci_build.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'gfx/MSXmerge/**'
      - '.github/workflows/msxmerge_ci_build.yml'

jobs:
  build:
    uses: ./.github/workflows/composer_template.yml
    with:
      tileset: MSX++UnDeadPeopleEdition_v2
      composer-args: --use-all
